<a href="https://colab.research.google.com/github/OllyMuh/Probability-Statistics/blob/main/The%20Relationship%20of%20Quantities.%20Correlation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

# Задача 1

Даны значения величины заработной платы заёмщиков банка (salary) и значения их поведенческого кредитного скоринга (scoring):

salary = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
scoring = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]
Найдите ковариацию этих двух величин: сначала без использования специальных функций, а затем с применением функции numpy.cov. Полученные значения должны быть равны.
Найдите коэффициент корреляции Пирсона: посредством ковариации и средних квадратических отклонений двух признаков, а затем применив специальные функции из библиотек numpy и pandas.

In [ ]:
salary = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110]
scoring = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]
salary = np.array(salary)
scoring = np.array(scoring)
# salary, scoring

(array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110]),
 array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832]))

In [ ]:
# ковариация зарплаты и скоринга по формуле
m_salary = salary.mean()
m_scoring = scoring.mean()
# cov = ((salary - m_salary) * (scoring - m_scoring)).mean()  #смещенная
# cov = (salary * scoring).mean() - m_salary * m_scoring  #смещенная
cov = ((salary - m_salary) * (scoring - m_scoring)).sum() / (salary.shape[0] - 1)  #несмещенная
cov
# 9157.84
# 10175.37777777778

10175.37777777778

In [ ]:
salary.var()

3494.6400000000003

In [ ]:
scoring.var()

30468.890000000007

In [ ]:
# ковариация по готовой функции numpy
np.cov(salary, scoring)

array([[ 3882.93333333, 10175.37777778],
       [10175.37777778, 33854.32222222]])

In [ ]:
# коэффициент корреляции Пирсона
corr = cov / (salary.std(ddof=True) * scoring.std(ddof=True))
corr

0.8874900920739164

In [ ]:
corr = np.corrcoef(salary, scoring)
corr

array([[1.        , 0.88749009],
       [0.88749009, 1.        ]])

In [ ]:
pd_corr = pd.DataFrame(data={'salary':salary, 'scoring':scoring}).corr()
pd_corr

salary  scoring
salary   1.00000  0.88749
scoring  0.88749  1.00000

# Задача 2

Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:

131, 125, 115, 122, 131, 115, 107, 99, 125, 111
Известно, что в генеральной совокупности IQ распределён нормально. Найдите доверительный интервал для математического ожидания с надёжностью 0.95.

In [ ]:
# обратное значение функции стандартного нормального распределения для надежности = 0.95 
f = 1.96

In [ ]:
iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])
iq

array([131, 125, 115, 122, 131, 115, 107,  99, 125, 111])

In [ ]:
# находим среднее и среднеквадратичное отклонение
m_iq = iq.mean()
std_iq = iq.std(ddof=True)
m_iq, std_iq

(118.1, 10.54566788359614)

In [ ]:
# находим величину выборки
n = iq.shape[0]
n

10

In [ ]:
# нижняя граница
T1 = m_iq - ((std_iq / np.sqrt(n)) * f)
T1

111.56372732786916

In [ ]:
# верхняя граница
T2 = m_iq + ((std_iq / np.sqrt(n)) * f)
T2

124.63627267213083

Ответ: доверительный интервал от 111,56 до 124,64

# Задача 3

Известно, что рост футболистов в сборной распределён нормально с известной дисперсией 25. На выборке объёма 27 выборочное среднее составило 174.2. Найдите доверительный интервал для математического ожидания с надёжностью 0.95.

In [ ]:
std = np.sqrt(25)
n = 27
m_sample = 174.2

In [ ]:
# обратное значение функции стандартного нормального распределения для надежности = 0.95 
f = 1.96

In [ ]:
# нижняя граница
T1 = m_sample - ((std / np.sqrt(n)) * f)
T1

172.31398912064722

In [ ]:
# верхняя граница
T2 = m_sample + ((std / np.sqrt(n)) * f)
T2

176.08601087935276

Ответ: доверительный интервал от 172,313 до 176,086